role_one = Role.create(character_name: "Tony Soprano")
role_two = Role.create(character_name: "Meadow")
role_three = Role.create(character_name: "Paulie")
role_four = Role.create(character_name: "Carmela")
role_five = Role.create(character_name: "Sil")

Audition.create(actor: "James", location: "NJ" , phone: 555, hired: false, role_id: role_one.id)
Audition.create(actor: "Edie", location: "Chicago", phone: 333, hired: false, role_id: role_four.id)
Audition.create(actor: "Michael", location: "LA", phone: 222, hired: false, role_id: role_five.id)
Audition.create(actor: "Sirico", location: "Houston", phone: 111, hired: false, role_id: role_three.id)
Audition.create(actor: "Jamie", location: "NY", phone: 777, hired: false, role_id: role_two.id)
Audition.create(actor: "Rebecca", location: "NY", phone: 777, hired: false, role_id: role_four.id)
Audition.create(actor: "Johnny", location: "NY", phone: 777, hired: false, role_id: role_one.id)
Audition.create(actor: "Ricardo", location: "NY", phone: 777, hired: false, role_id: role_five.id)